version: 2

updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '06:00'
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 1
    labels:
      - dependencies
      - python
    groups:
      python-safe-updates:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
      time: '06:30'
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 1
    labels:
      - dependencies
      - docker
    ignore:
      - dependency-name: python
        update-types:
          - version-update:semver-major
          - version-update:semver-minor

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: '07:00'
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 1
    labels:
      - dependencies
      - github-actions
    groups:
      actions-safe-updates:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
